package com.mobius.software.telco.protocols.diameter.primitives.creditcontrol.huawei;
/*
 * Mobius Software LTD
 * Copyright 2023, Mobius Software LTD and individual contributors
 * by the @authors tag.
 *
 * This program is free software: you can redistribute it and/or modify
 * under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation; either version 3 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 */

import com.mobius.software.telco.protocols.diameter.HuaweiAvpCodes;
import com.mobius.software.telco.protocols.diameter.VendorIDs;
import com.mobius.software.telco.protocols.diameter.annotations.DiameterAvpDefinition;
import com.mobius.software.telco.protocols.diameter.primitives.DiameterUnsigned32;

/**
*
* @author yulian oifa
*
*/
/*
 * 	3.2.132  Total-Cost-Flag AVP
	
	AVP Name
	Total-Cost-Flag

	AVP Code
	20375

	AVP Data Type
	Unsigned32

	Vendor ID
	2011

	Description
	Indicates the flag of returning the fee generated by a call. 

	The values are as follows:
    	- 0: Not return the consumption result.
    	- 1: Return the total cost information.

	When this mode is used, the fee items are not differentiated. That is, only one Cost-Information AVP group exists, which can be compatible with the standard Cost-Information AVP group.
 */
@DiameterAvpDefinition(code = HuaweiAvpCodes.TOTAL_COST_FLAG, vendorId = VendorIDs.HUAWEI_ID, name = "Total-Cost-Flag")
public interface TotalCostFlag extends DiameterUnsigned32
{
}