package com.mobius.software.telco.protocols.diameter.primitives.accounting;
/*
 * Mobius Software LTD
 * Copyright 2023, Mobius Software LTD and individual contributors
 * by the @authors tag.
 *
 * This program is free software: you can redistribute it and/or modify
 * under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation; either version 3 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 */

import java.util.List;

import com.mobius.software.telco.protocols.diameter.TgppAvpCodes;
import com.mobius.software.telco.protocols.diameter.VendorIDs;
import com.mobius.software.telco.protocols.diameter.annotations.DiameterAvpDefinition;
import com.mobius.software.telco.protocols.diameter.exceptions.MissingAvpException;
import com.mobius.software.telco.protocols.diameter.primitives.DiameterAvp;
import com.mobius.software.telco.protocols.diameter.primitives.rx.Flows;

import io.netty.buffer.ByteBuf;

/**
*
* @author yulian oifa
*
*/

/*
 * 	7.2.11	AF-Correlation-Information AVP
	The AF-Correlation-Information AVP (AVPcode 1276) is of type Grouped and includes the "AF Charging Identifier" (ICID for IMS)  and associated  flow identifiers generated by the AF and received by P-GW over Rx/Gx as defined in TS 29.214 [214] and TS 29.212 [215]. The AF-Correlation-Information is defined per Rating Group or per Rating Group and Service Identifier when Service Identifier level reporting applies.
	When several AF sessions (refer to TS 29.214 [214]) are conveyed over the same bearer, this AVP may appear several times per MSCC instance.
	It has the following ABNF grammar:
	
	AF-Correlation-Information:: =  < AVP Header: 1276 >
	  		{ AF-Charging-Identifier }
		* 	[ Flows ]
 */
@DiameterAvpDefinition(code = TgppAvpCodes.AF_CORRELATION_INFORMATION, vendorId = VendorIDs.TGPP_ID, name = "AF-Correlation-Information")
public interface AFCorrelationInformation extends DiameterAvp
{
	ByteBuf getAFChargingIdentifier();
	
	void setAFChargingIdentifier(ByteBuf value) throws MissingAvpException;
	
	List<Flows> getFlows();
	
	void setFlows(List<Flows> value);
}