package com.mobius.software.telco.protocols.diameter.primitives.accounting;
/*
 * Mobius Software LTD
 * Copyright 2023, Mobius Software LTD and individual contributors
 * by the @authors tag.
 *
 * This program is free software: you can redistribute it and/or modify
 * under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation; either version 3 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 */

import com.mobius.software.telco.protocols.diameter.TgppAvpCodes;
import com.mobius.software.telco.protocols.diameter.VendorIDs;
import com.mobius.software.telco.protocols.diameter.annotations.DiameterAvpDefinition;
import com.mobius.software.telco.protocols.diameter.primitives.DiameterOctetString;

/**
*
* @author yulian oifa
*
*/
/*
 * 	7.2.111E Network-Call-Reference-Number AVP
	The Network-Call-Reference-Number AVP (AVP code 3418) is type OctetString and contains the reference number
	generated by the GMSC/MSC for the voice call service. When combined with the identity of the MSC that allocated it
	can be used to unambiguously identify the call. 
 */
@DiameterAvpDefinition(code = TgppAvpCodes.NETWORK_CALL_REFERENCE_NUMBER, vendorId = VendorIDs.TGPP_ID, name = "Network-Call-Reference-Number")
public interface NetworkCallReferenceNumber extends DiameterOctetString
{
}