package com.mobius.software.telco.protocols.diameter.primitives.accounting;
/*
 * Mobius Software LTD
 * Copyright 2023, Mobius Software LTD and individual contributors
 * by the @authors tag.
 *
 * This program is free software: you can redistribute it and/or modify
 * under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation; either version 3 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 */

import com.mobius.software.telco.protocols.diameter.TgppAvpCodes;
import com.mobius.software.telco.protocols.diameter.VendorIDs;
import com.mobius.software.telco.protocols.diameter.annotations.DiameterAvpDefinition;
import com.mobius.software.telco.protocols.diameter.primitives.DiameterUTF8String;

/**
*
* @author yulian oifa
*
*/
/*
 * 	7.2.123 Originating-IOI AVP
	The Originating-IOI AVP (AVP code 839) is of type UTF8String (alphanumeric string) and holds the Inter Operator
	Identifier (IOI) for the originating network as generated by the IMS Network Element which takes responsibility for
	populating this parameter in a SIP request as described in RFC 7315 [404] and TS 24.229 [202]. The Originating IOI
	contains the following values:

	Type 1 IOI

	- IOI of the visited network where the P-CSCF is located for SIP requests directed to the SCSCF when initiated by the served user
	- IOI of the home network where the S-CSCF is located for SIP requests directed to the TRF in
	  the visited network when "VPLMN routing" is applied in a Roaming Architecture for Voice
	  over IMS with Local breakout.
	- IOI of the home network where the S-CSCF is located for SIP requests directed to the visited
	  network P-CSCF when terminated at the served user..

	Type 2 IOI

	- IOI of the home network of the originating end user where the S-CSCF is located in case a
	  session is initiated from the IMS. In case of redirection by the S-CSCF, Originating-IOI AVP
	  indicates the terminating party's network operator from which the session is redirected.
	- IOI of the visited network when "VPLMN routing" is applied in a Roaming Architecture for
	  Voice over IMS with Local breakout.
	- IOI of the originating network where the MGCF is located in case a session is initiated from
	  the PSTN toward the IMS.
	
	Type 3 IOI
	
	- IOI of the home network (originating side or terminating side) where the S-CSCF is located
	  when forwarding a SIP request as described in TS 24.229 [202] to an AS (proxy, terminating
	  UA or redirect server or B2BUA).
	- IOI of the service provider network where the AS is located when an AS (originating UA or
	  B2BUA) initiates a SIP request as described in TS 24.229 [202].
	  For further details on the Type 1, Type 2 and Type 3 IOIs, please refer to TS 32.240 [1]. 
 */
@DiameterAvpDefinition(code = TgppAvpCodes.ORIGINATING_IOI, vendorId = VendorIDs.TGPP_ID, name = "Originating-IOI")
public interface OriginatingIOI extends DiameterUTF8String
{
}