package com.mobius.software.telco.protocols.diameter.primitives.accounting;
/*
 * Mobius Software LTD
 * Copyright 2023, Mobius Software LTD and individual contributors
 * by the @authors tag.
 *
 * This program is free software: you can redistribute it and/or modify
 * under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation; either version 3 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 */

import com.mobius.software.telco.protocols.diameter.annotations.DiameterAvpDefinition;
import com.mobius.software.telco.protocols.diameter.primitives.DiameterUTF8String;
import com.mobius.software.telco.protocols.diameter.primitives.KnownVendorIDs;

/**
*
* @author yulian oifa
*
*/
/*
 * 	7.2.146 PoC-Session-Id AVP
	The PoC-Session-Id AVP (AVP code 1229) is of type UTF8String. It uniquely identifies an end-to-end PoC session and
	may be used for correlation between charging information generated by participating and controlling PoC functions.
	This information is obtained from the "Contact" header of the SIP message received from the controlling PoC function.
	
	NOTE: The PoC-Session-Id may not be available in the initial charging interactions for the PoC session. 
 */
@DiameterAvpDefinition(code = 1229L, vendorId = KnownVendorIDs.TGPP_ID, name = "PoC-Session-Id")
public interface PoCSessionId extends DiameterUTF8String
{
}