package com.mobius.software.telco.protocols.diameter.primitives.accounting;
/*
 * Mobius Software LTD
 * Copyright 2023, Mobius Software LTD and individual contributors
 * by the @authors tag.
 *
 * This program is free software: you can redistribute it and/or modify
 * under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation; either version 3 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 */

import com.mobius.software.telco.protocols.diameter.annotations.DiameterAvpDefinition;
import com.mobius.software.telco.protocols.diameter.primitives.DiameterUTF8String;
import com.mobius.software.telco.protocols.diameter.primitives.KnownVendorIDs;

/**
*
* @author yulian oifa
*
*/
/*
 * 	7.2.233B Transit-IOI-List AVP
	The Transit-IOI-List AVP (AVP code 2701) is of type UTF8String and holds the Inter Operator Identifiers (IOI) for the
	transit networks as generated by the IMS Network Elements which take responsibility for populating this parameter in a
	SIP request and response as described in RFC 7315 [404] and TS 24.229 [202]. Multiple occurrences of this AVP shall
	be in chronological order, i.e. the value in the SIP request is listed first. If only a value for the SIP response is available,
	the Transit-IOI-List for the SIP request shall be included with the value "unknown". 
 */
@DiameterAvpDefinition(code = 2701L, vendorId = KnownVendorIDs.TGPP_ID, name = "Transit-IOI-List")
public interface TransitIOIList extends DiameterUTF8String
{
}