package com.mobius.software.telco.protocols.diameter.primitives.accounting;

import java.util.HashMap;
import java.util.Map;

import com.mobius.software.telco.protocols.diameter.primitives.IntegerEnum;

/*
 * Mobius Software LTD, Open Source Cloud Communications
 * Copyright 2023, Mobius Software LTD and individual contributors
 * by the @authors tag.
 *
 * This program is free software: you can redistribute it and/or modify
 * under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation; either version 3 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 */
/**
*
* @author yulian oifa
*
*/
/*
 * 	7.2.238 Type-Number AVP
	The Type-Number AVP (AVP code 1204) is of type Enumerated and identifies the well-known media types. The values
	are taken from OMNA WSP Content Type Numbers [210]. 
 */
public enum TypeNumberEnum implements IntegerEnum
{
	ANY(0),TEXT(1),TEXT_HTML(2),TEXT_PLAIN(3),TEXT_XHDML(4),TEXT_XTTML(5),TEXT_XVCALENDAR(6),TEXT_XVCARD(7),TEXT_VND_WAP_WML(8),TEXT_VND_WAP_WMLSCRIPT(9),
	TEXT_VND_WAP_WTA_EVENT(10),MULTIPART_MIXED(12),MULTIPART_FORMDATA(13),MULTIPART_BYTERANTES(14),MULTIPART_ALTERNATIVE(15),APPLICATION(16),
	APPLICATION_JAVA_VM(17),APPLICATION_X_WWW_FORM_URLENCODED(18),APPLICATION_XHDMLC(19),APPLICATION_VND_WAP_WMLC(20),APPLICATION_VND_WAP_WMLCSCRIPT(21),
	APPLICATION_VND_WAP_WTA_EVENTC(22),APPLICATION_VND_WAP_UAPROF(23),APPLICATION_VND_WAP_WTLS_CA_CERTIFICATE(24),APPLICATION_VND_WAP_WTLS_USER_CERTIFICATE(25),
	APPLICATION_X509_CA_CERT(26),APPLICATION_X509_USER_CERT(27),IMAGE(28),IMAGE_GIF(29),IMAGE_JPEG(30),IMAGE_TIFF(31),IMAGE_PNG(32),IMAGE_VND_WAP_WBMP(33),
	APPLICATION_VND_WAP_MULTIPART(34),APPLICATION_VND_WAP_MULTIPART_MIXED(35),APPLICATION_VND_WAP_MULTIPART_FORM_DATA(36),APPLICATION_VND_WAP_MULTIPART_BYTERANGES(37),
	APPLICATION_VND_WAP_MULTIPART_ALTERNATIVE(38),APPLICATION_XML(39),TEXT_XML(40),APPLICATION_VND_WAP_WBXML(41),APPLICATION_X968_CROSS_CERT(42),
	APPLICATION_X968_CA_CERT(43),APPLICATION_X968_USER_CERT(44),TEXT_VND_WAP_SI(45),APPLICATION_VND_WAP_SIC(46),TEXT_VND_WAP_SL(47),APPLICATION_VND_WAP_SLC(48),
	TEXT_VND_WAP_CO(49),APPLICATION_VND_WAP_COC(50),APPLICATION_VND_WAP_MULTIPART_RELATED(51),APPLICATION_VND_WAP_SIA(52),TEXT_VND_WAP_CONNECTIVITY_XML(53),
	APPLICATION_VND_WAP_CONNECTIVITY_WBXML(54),APPLICATION_PKCS7_MIME(55),APPLICATION_VND_WAP_HASHED_CERTIFICATE(56),APPPLICATION_VND_WAP_CERT_RESPONSE(58),
	APPLICATION_XHTML_XML(59),APPLICATION_WML_XML(60),TEXT_CSS(61),APPLICATION_VND_WAP_MMS_MESSAGE(62),APPLICATION_VND_WAP_ROLLOVER_CERTIFICATE(63),
	APPLICATION_VND_WAP_LOCC_WBXML(64),APPLICATION_VND_WAP_LOC_XML(65),APPLICATION_VND_SYNCML_DM_WBXML(66),APPLICATION_VND_SYNCML_DM_XML(67),
	APPLICATION_VND_SYNCML_NOTIFICATION(68),APPLICATION_VND_WAP_XHTML_XML(69),APPLICATION_VND_WV_CSP_CIR(70),APPLICATION_VND_OMA_DD_XML(71),
	APPLICATION_VND_OMA_DRM_MESSAGE(72),APPLICATION_VND_OMA_DRM_CONTENT(73),APPLICATION_VND_OMA_DRM_RIGHTS_XML(74),APPLICATION_VND_OMA_DRM_RIGHTS_WBXML(75),
	APPLICATION_VND_WV_CSP_XML(76),APPLICATION_VND_WV_CSP_WBXML(77),APPLICATION_VND_SYNCML_DS_NOTIFICATION(78),AUDIO(79),VIDEO(80),APPLICATION_VND_OMA_DD2_XML(81),
	APPLICATION_MIKEY(82),APPLICATION_VND_OMA_DCD(83),APPLICATION_VND_OMA_DCDC(84),TEXT_XVMESSAGE(85),APPLICATION_VND_OMADS_EMAIL_WBXML(86),TEXT_VBOOKMARK(87),
	APPLICATION_VND_SYNCML_DM_NOTIFICATION(88),APPLICATION_OCTET_STREAM(90),APPLICATION_JSON(91),
	
	APPLICATION_VND_UPLANET_CACHEOP_WBXML(0x0201),APPLICATION_VND_UPLANET_SIGNAL(0x0202),APPLICATION_VND_UPLANET_ALERT_WBXML(0x0203),
	APPLICATION_VND_UPLANET_LISTCMD_WBXML(0x0204),APPLICATION_VND_UPLANET_LISTCMD_WBXML_2(0x0205),APPLICATION_VND_UPLANET_CHANNEL_WBXML(0x0206),
	APPLICATION_VND_UPLANET_PROVISIONING_STATUS_URI(0x0207),XWAP_MULTIPART_VND_UPLANET_HEADER_SET(0x0208),APPLICATION_VND_UPLANET_BEARER_CHOICE_WBXML(0x0209),
	APPLICATION_VND_PHONECOM_MMC_WBXML(0x020A),APPLICATION_VND_NOKIA_SYNCSET_WBXML(0x020B),IMAGE_X_UP_WPNG(0x020C),
	
	APPLICATION_IOTA_MMC_WBMXL(0x0300),APPLICATION_IOTA_MMC_MXL(0x0301),APPLICATION_VND_SYNCML_XML(0x0302),APPLICATION_VND_SYNCML_WBXML(0x0303),
	TEXT_VND_WAP_EMN_XML(0x0304),TEXT_CALENDAR(0x0305),APPLICATION_VND_OMADS_EMAIL_XML(0x0306),APPLICATION_VND_OMADS_FILE_XML(0x0307),
	APPLICATION_VND_OMADS_FOLDER_XML(0x0308),TEXT_DIRECTORY_PROFILE_VCARD(0x0309),APPLICATION_VND_WAP_EMN_WBXML(0x030A),KARINA_TEREKHOVA(0x030B),
	APPLICATION_VND_MOTOROLA_SCREEN3_XML(0x030C),APPLICATION_VND_MOTOROLA_SCREEN3_GZIP(0x030D),APPLICATION_VND_CMCC_SETTING_WBXML(0x030E),
	APPLICATION_VND_CMCC_BOMBING_WBXML(0x030F),APPLICATION_VND_DOCOMO_PF(0x0310),APPLICATION_VND_DOCOMO_UB(0x0311),APPLICATION_VND_OMALOC_SUPL_INIT(0x0312),
	APPLICATION_VND_OMA_GROUP_USAGE_LIST_XML(0x0313),APPLICATION_OMA_DIRECTORY_XML(0x0314),APPLICATION_VND_DOCOMO_PF2(0x0315),
	APPLICATION_VND_OMA_DRM_ROAP_TRIGGER_WBXML(0x0316),APPLICATION_VND_SBM_MID2(0x0317),APPLICATION_VND_WMF_BOOTSTRAP(0x0318),APPLICATION_VND_CMCC_DCD_XML(0x0319),
	APPLICATION_VND_SBM_CID(0x031A),APPLICATION_VND_OMA_BCAST_PROVISIONINGTRIGGER(0x031B),APPLICATION_VND_DOCOMO_DM(0x031C),
	APPLICATION_VND_OMA_SCIDM_MESSAGES_XML(0x031D),APPLICATION_VND_INNOPATH_WAMP_NOTIFICATION(0x031E);

	private static final Map<Integer, TypeNumberEnum> intToTypeMap = new HashMap<Integer, TypeNumberEnum>();
	static 
	{
	    for (TypeNumberEnum type : TypeNumberEnum.values()) 
	    {
	    	intToTypeMap.put(type.value, type);
	    }
	}

	public static TypeNumberEnum fromInt(Integer value) 
	{
		TypeNumberEnum type = intToTypeMap.get(value);
	    return type;
	}
	
	private int value;
	
	private TypeNumberEnum(int value)
	{
		this.value=value;
	}
	
	public int getValue()
	{
		return value;
	}
}
